# mono changes start

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: Magazine8x65mmEmpty
  result: Magazine8x65mmEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: Magazine8x65mmSKR
  result: Magazine8x65mmSKR
  materials:
    Steel: 650

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: AmmoBox8x65mmSKR
  result: AmmoBox8x65mmSKR
  materials:
    Steel: 1200
